
env:
  LC_CTYPE: "UTF-8"

window:
  dimensions:
    columns: 80
    lines: 25

font:
  normal: 
    family: Meslo LG S Regular for Powerline
    style: Regular

  bold:
    family: Meslo LG S Bold for Powerline

  italic:
    family: Meslo LG S Italic for Powerline

  size: 14.0

schemes:
  solarized-ligth: &light
    primary:
      background: '0x002b36'
      foreground: '0x839496'
    normal:
      black:   '0x073642'
      red:     '0xdc322f'
      green:   '0x859900'
      yellow:  '0xb58900'
      blue:    '0x268bd2'
      magenta: '0xd33682'
      cyan:    '0x2aa198'
      white:   '0xeee8d5'
    bright:
      black:   '0x002b36'
      red:     '0xcb4b16'
      green:   '0x586e75'
      yellow:  '0x657b83'
      blue:    '0x839496'
      magenta: '0x6c71c4'
      cyan:    '0x93a1a1'
      white:   '0xfdf6e3'
  
  Tomorrow Night Eighties: &tomorrow-eighties
    primary:
      background: '0x3b3b3b' 
      foreground: '0xd5d5d5'
    normal:
      black:   '0x000000'
      red:     '0xf68d8c'
      green:   '0xa7d3a9'
      yellow:  '0xffd478'
      blue:    '0x77aad5'
      magenta: '0xd6acd5'
      cyan:    '0x75d4d5'
      white:   '0xfefefe'
    bright:
      black:   '0x000000'
      red:     '0xf68d8c'
      green:   '0xa7d3a9'
      yellow:  '0xffd478'
      blue:    '0x77aad5'
      magenta: '0xd6acd5'
      cyan:    '0x75d4d5'
      white:   '0xfefefe'

colors: *tomorrow-eighties

key_bindings:
  - { key: Key0,   mods: Command,         action: ResetFontSize    }
  - { key: Equals, mods: Command,         action: IncreaseFontSize }
  - { key: Add,    mods: Command,         action: IncreaseFontSize }
  - { key: Minus,  mods: Command,         action: DecreaseFontSize }
  - { key: K,      mods: Command,         action: ClearHistory     }
  - { key: K,      mods: Command,         chars: "\x0c"            }
  - { key: V,      mods: Command,         action: Paste            }
  - { key: C,      mods: Command,         action: Copy             }
  - { key: H,      mods: Command,         action: Hide             }
  - { key: M,      mods: Command,         action: Minimize         }
  - { key: Q,      mods: Command,         action: Quit             }
  - { key: W,      mods: Command,         action: Quit             }
  - { key: F,      mods: Command|Control, action: ToggleFullscreen }
  - { key: Paste,                    action: Paste                            }
  - { key: Copy,                     action: Copy                             }
  - { key: L,         mods: Control, action: ClearLogNotice                   }
  - { key: L,         mods: Control, chars: "\x0c"                            }
  - { key: PageUp,    mods: Shift,   action: ScrollPageUp,   mode: ~Alt       }
  - { key: PageDown,  mods: Shift,   action: ScrollPageDown, mode: ~Alt       }
  - { key: Home,      mods: Shift,   action: ScrollToTop,    mode: ~Alt       }
  - { key: End,       mods: Shift,   action: ScrollToBottom, mode: ~Alt       }
  - { key: N,         mods: Command,      action: SpawnNewInstance       }
  - { key: Space,     mods: Alt,          chars: " "                     }